/*
    Nathanael Gastelum
    March 17, 2020
    Purpose: This program takes the file generated by the Sales program and generates a new text file for each category
    Inputs: One Command Line argument fot the path to sales.txt
    Outputs: One text file for each category in the sales file
    */

import java.io.*;
import java.util.Scanner;

public class Categorizer {

    public static void main(String[] args) {

        // Handle command line arguments
        if(args.length < 1) {
            System.out.println("No arguments, use \"h\" for help");
            return;
        }

        if (args[0].equals("h")) {
            System.out.println("Needs file path argument: source");
            return;
        }

        String inFilePath;

        try {
            inFilePath = args[0];
        } catch (Exception e) {
            System.out.println("Not enough arguments");
            return;
        }

        File inFile = new File(inFilePath);
        Scanner input;

        try {
            input = new Scanner(inFile);
        } catch (FileNotFoundException e) {
            System.out.println(inFilePath + " does not exist ");
            return;
        }

        // Write to files based on category
        while (input.hasNextLine()) {
            String outString  = input.nextLine();
            String[] outStrings = outString.split(";");

            String outFilePath = outStrings[1] + ".txt";

            try {
                FileWriter output = new FileWriter(outFilePath, true);
                output.write(outString + "\n");
                output.close();
            } catch (IOException e) {
                System.out.println("Unable to write to file");
            }
        }
    }
}